version: '3'

services:
  backend:
    build:
      context: ./docker/backend/php-7.3
    volumes:
      - ./:/var/www
      - ./docker/backend/php-7.3/php.ini:/usr/local/etc/php/conf.d/90-php.ini
      - ./docker/backend/php-7.3/opcache.ini:/usr/local/etc/php/conf.d/91-opcache.ini
      - ./docker/backend/php-7.3/xdebug.ini:/usr/local/etc/php/conf.d/92-xdebug.ini
      - ./docker/backend/php-7.3/entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
      - .env.local
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}"
      - APP_ENV=${BACKEND_ENV:-dev}
      - FROM_SCRATCH=${FROM_SCRATCH:-N}
    user: "www-data:www-data"
    entrypoint: /entrypoint.sh
    depends_on: [database]
  frontend:
    image: node:latest
    user: node
    working_dir: /home/node/app
    env_file:
      - .env
      - .env.local
    environment:
      - NODE_ENV=${FRONTEND_ENV-dev}
    volumes:
      - ./:/home/node/app
    expose: [8081]
    command: npm run container-start-${FRONTEND_ENV:-dev}
  webserver:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/webserver/nginx/default.conf:/etc/nginx/default.conf
    ports:
      - 80:80
    env_file:
      - .env
      - .env.local
    environment:
      - NGINX_HOST=${HOSTNAME_MASK}
    command: /bin/bash -c "envsubst < /etc/nginx/default.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on: [backend]
  database:
    image: mysql:5.7
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
      - .env.local
    environment:
      MYSQL_DATABASE:       ${DATABASE_NAME}
      MYSQL_USER:           ${DATABASE_USER}
      MYSQL_PASSWORD:       ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${DATABASE_ROOT_PASSWORD}
